IOC_NAME="iocDualTimingARInjection"
IOC_USER="lucasrusso"
IOC_GROUP="users"
IOC_CHDIR="/home/lxusers/l/lucasrusso/repos/siocDualTiming/iocBoot/iocDualTimingARInjection"
IOC_PORT=""
IOC_CMD="./st.cmd"
EPICS_CA_ADDR_LIST="127.255.255.255 192.168.1.2 192.168.1.3"
