#ifndef __TIMINGSEQUENCEDEFS_H__
#define __TIMINGSEQUENCEDEFS_H__

#include "timingSequenceConstants.h"

/**
 * timingSequenceDefs.h
 * Types and constants used by the ALS Timing System Sequencer.
 *
 * April 2015
 * Bob Gunion
 */

typedef enum {
	DEFAULT_MODE = 0,
	LINACTUNE_MODE = 10,
	BRTUNE_MODE = 20,
	BTSTUNE_MODE = 30,
	SRINJECTION_MODE = 40,
	SRINJECTION_PREPARE_MODE = 41
} MODES;

typedef enum {
	DEFAULT_MODE_INDEX,
	LINACTUNE_MODE_INDEX,
	BRTUNE_MODE_INDEX,
	BTSTUNE_MODE_INDEX,
	SRINJECTION_MODE_INDEX,
	SRINJECTION_PREPARE_MODE_INDEX
} MODE_INDEXES;

//extern unsigned char modeEvtCodes[NUM_MODES][MAX_SEQUENCE_LENGTH];

long tsOffsets[NUM_EVTCODES];

/**
 * Sequencer States: TimSeqState
 */
typedef enum {
    NOT_RUNNING,
	DEFAULT_SEQUENCE,
	WAIT_FOR_EOS,
	WAIT_FOR_START,
	WAIT_FOR_EXTRACTION,
	WAIT_FOR_REQUEST,
	PROCESS_REQUEST,
	VALIDATE_REQUEST,
	CHECK_BEAMCURRENT,
	CHECK_SEVERITIES,
	CHECK_FIBER_LINKS,
	LOAD_REQUESTED_SEQUENCE,
	WAIT_FOR_POTENTATE,
	WAIT_FOR_SEVERITY,
	INCREMENT_BAD_COUNT,
} SEQUENCER_STATES;


#endif // __TIMINGSEQUENCEDEFS_H__

